<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.3.0</Version>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <PlatformTarget>x64</PlatformTarget>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <Configurations>Debug;Release</Configurations>
    <DebugType>embedded</DebugType>
    <NoWarn>
		1701;
	    1702;
	    RCS1037;
	    CS0436;
	    CS1591
	</NoWarn>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="libraries\*" />
    <EmbeddedResource Remove="libraries\*" />
    <Compile Remove="libraries\*" />

    <Reference Include="libraries/*.dll">
      <Private>false</Private>
    </Reference>
  </ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Assets/*">
			<LogicalName>$([System.String]::Copy('$(RootNamespace).Assets.%(RecursiveDir)%(FileName)%(Extension)').Replace('\', '.').Replace('/', '.'))</LogicalName>
		</EmbeddedResource>
	</ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>
</Project>
